name: ${project.name}
main: ${project.groupId}.${project.artifactId}.PluginMentionBeep
version: ${project.version}
commands:
  MentionBeep:
    description: ${project.description}
    usage: To get help, run /MentionBeep or /mb without any arguments. The sender must be an online player.
    aliases: [mb]